#!/bin/bash

echo "🧹 Limpando deployments do Render..."

echo "📋 Para limpar deployments do Render, você precisa:"
echo ""
echo "1. 🌐 Acessar: https://dashboard.render.com/"
echo "2. 🔐 Fazer login na sua conta"
echo "3. 📱 Ir para 'Services' no menu lateral"
echo "4. 🗑️  Deletar os serviços relacionados ao projeto:"
echo "   - video-translate-backend"
echo "   - assemblyai-websocket-proxy"
echo "   - deepgram-websocket-proxy"
echo "   - Qualquer outro serviço relacionado"
echo ""
echo "5. 📂 Ir para 'Static Sites' (se houver)"
echo "6. 🗑️  Deletar sites estáticos relacionados"
echo ""
echo "⚠️  ATENÇÃO: Esta ação é irreversível!"
echo "💡 Certifique-se de fazer backup de dados importantes antes de deletar"
echo ""
echo "🔗 Links úteis:"
echo "   - Dashboard: https://dashboard.render.com/"
echo "   - Documentação: https://render.com/docs"

echo "✅ Instruções de limpeza do Render fornecidas!"