#!/bin/bash

echo "🚀 Deploy Manual no Render - Guia Passo a Passo"
echo "================================================"
echo ""

echo "📋 OPÇÃO 1: Dashboard do Render (Recomendado)"
echo "1. Acesse: https://dashboard.render.com/"
echo "2. Clique em 'New +' → 'Web Service'"
echo "3. Conecte o repositório: grimmreaperb-design/video-translate-app"
echo "4. Configure:"
echo "   - Name: video-translate-backend"
echo "   - Environment: Node"
echo "   - Region: Oregon (US West)"
echo "   - Branch: main"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm start"
echo "5. Adicione variáveis de ambiente:"
echo "   - NODE_ENV = production"
echo "   - PORT = 10000"
echo "   - FRONTEND_URL = https://video-translate-app.vercel.app"
echo "6. Health Check Path: /api/health"
echo ""

echo "📋 OPÇÃO 2: Blueprint (render.yaml)"
echo "1. Acesse: https://dashboard.render.com/"
echo "2. Clique em 'New +' → 'Blueprint'"
echo "3. Conecte o repositório: grimmreaperb-design/video-translate-app"
echo "4. O Render detectará automaticamente o render.yaml"
echo ""

echo "📋 OPÇÃO 3: Verificar se já existe um serviço"
echo "1. Acesse: https://dashboard.render.com/"
echo "2. Procure por 'video-translate-backend'"
echo "3. Se existir, clique em 'Manual Deploy'"
echo ""

echo "🔗 Links úteis:"
echo "- Dashboard: https://dashboard.render.com/"
echo "- Documentação: https://render.com/docs"
echo "- Status do GitHub Actions: https://github.com/grimmreaperb-design/video-translate-app/actions"
echo ""

echo "✅ Após o deploy, teste em:"
echo "https://video-translate-backend.onrender.com/api/health"