#!/bin/bash

echo "🚀 Deploying Backend to Render.com..."

echo "📋 Instruções para Deploy no Render:"
echo ""
echo "1. Acesse: https://render.com"
echo "2. Conecte seu GitHub"
echo "3. Crie um novo Web Service"
echo "4. Conecte este repositório"
echo "5. Configure:"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm start"
echo "   - Environment: Node"
echo ""
echo "6. Adicione as variáveis de ambiente:"
echo "   - PORT=10000"
echo "   - NODE_ENV=production"
echo "   - FRONTEND_URL=https://video-translate-app.vercel.app"
echo ""
echo "7. Após deploy, copie a URL (ex: https://video-translate-backend.onrender.com)"
echo ""
echo "✅ O Render.com oferece 750 horas gratuitas por mês!"
echo "🔗 Documentação: https://render.com/docs/web-services"