services:
  - type: web
    name: video-translate-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://video-translate-app.vercel.app
    healthCheckPath: /api/health